dbt_training:
  outputs:
    dev:
      account: yl45797.east-us-2.azure
      database: analytics_116
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: developer_116
      schema: dbt_dev
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_USER') }}"
      warehouse: developer_wh_116
    ci:
      account: yl45797.east-us-2.azure
      database: analytics_116
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: developer_116
      schema: dbt_ci
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_USER') }}"
      warehouse: developer_wh_116
    prod:
      account: yl45797.east-us-2.azure
      database: analytics_116
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: developer_116
      schema: dbt_prod
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_USER') }}"
      warehouse: developer_wh_116
  target: dev
